[book]
title = "Info · Ihaveacat"
description = "Interesting posts, notes, tools, and resources found in the wild."
language = "en"
src = "info"

[build]
build-dir = "book"
create-missing = false

[output.html]
no-section-label = true
sidebar-header-nav = false
