name: Deploy 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update Server Repo
      uses: fxkjd/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
      with:
        args: /opt/deploy/run
