name: Build & Deploy 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Build docker image
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ihaveacat-info:$(date +%s)
    # Deploy to server
    - name: Deploy to Server
      uses: fxkjd/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
      with:
        args: /opt/deploy/run
